
import DesignPackage.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author zalve
 */
public class SudokuPanel extends javax.swing.JPanel {

    /**
     * Creates new form SudokuPanel
     */
     private Properties prop = new Properties();
    public SudokuPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(21, 32, 43));
        setLayout(null);

        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(400, 710, 190, 40);

        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(210, 710, 190, 40);

        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(0, 710, 210, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/t5.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 710, 1360, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                     
                
                FloodFillAlgorithm panel = new FloodFillAlgorithm();
                MainPanel main = new MainPanel();
                for(int i = 0 ; i < prop.paintWidth ;i++)
                for(int j = 0 ; j <prop.paintHeight ; j++)
                    prop.painBoard[i][j] = 1;
            // panel.setVisible(true);

                prop.board =  new int[ prop.ROWS][prop.COLUMNS];

               main. frame.getContentPane().removeAll();

                // refresh the panel.
                 main.frame.add(panel);
                 main.frame.setVisible(true);
                 ImageIcon img = new ImageIcon("src\\DSicon.png");
                 main.frame.setIconImage(img.getImage());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      PathFinderInterface panel = new PathFinderInterface();
                MainPanel main = new MainPanel();
                for(int i = 0 ; i < prop.paintWidth ;i++)
                for(int j = 0 ; j <prop.paintHeight ; j++)
                    prop.painBoard[i][j] = 1;
                // panel.setVisible(true);

                prop.board =  new int[ prop.ROWS][prop.COLUMNS];

                main. frame.getContentPane().removeAll();

                // refresh the panel.
                 main.frame.add(panel);
                 main.frame.setVisible(true);
                 ImageIcon img = new ImageIcon("src\\DSicon.png");
                 main.frame.setIconImage(img.getImage());
                 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            removeAll();
            removeAll();
            updateUI();
          
            
            prop.board =  new int[ prop.ROWS][prop.COLUMNS];
            
            
            MainPanel panel = new MainPanel();
            panel.setVisible(true);

            try {
                panel.main(new String[]{});
            } catch (Exception ex) {
                Logger.getLogger(PathFinderInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
